### ISSUE TITLE
why

### ISSUE THREAD

**Issue by jtyoui** [stucco/docs#4]
java.lang.NullPointerException: Missing environment variable STUCCO_DB_TYPE
        at gov.pnnl.stucco.schema.IndexDefinitionsToDB.main(IndexDefinitionsToDB.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)

**Comment by mikeiannacone** [comment]
`STUCCO_DB_TYPE` is an env variable, which should normally be set to `POSTGRESQL`

This is normally something that the install process should take care of; what install process are you using?
